spring.application.name=codedraft
app.data.profile-file=data/profile.json
app.data.courses-file=data/courses.json
app.data.catalog-file=data/catalog.json
app.experience.points-per-progress-update=5
server.error.include-stacktrace=never
