spring.application.name=codedraft
app.data.profile-file=data/profile.json
app.data.courses-file=data/courses.json
app.data.catalog-file=data/catalog.json
app.data.study-sessions-file=data/study_sessions.json
server.error.include-stacktrace=never
